///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SaveImage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SaveFullScreen recording.
    /// </summary>
    [TestModule("320f23d3-03bc-4c40-8690-a70826297057", ModuleType.Recording, 1)]
    public partial class SaveFullScreen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SaveImageRepository repository.
        /// </summary>
        public static SaveImageRepository repo = SaveImageRepository.Instance;

        static SaveFullScreen instance = new SaveFullScreen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SaveFullScreen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SaveFullScreen Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveFullScreen.Text1001' at 780;7.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(0));
            repo.SaveFullScreen.Text1001.DoubleClick("780;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(1));
            repo.SaveFullScreen.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen'.", new RecordItemIndex(2));
            Keyboard.Press("D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(3));
            repo.SaveFullScreen.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveFullScreen' at Center.", repo.SnapXAutoRunModeUntitled.SaveFullScreenInfo, new RecordItemIndex(4));
            repo.SnapXAutoRunModeUntitled.SaveFullScreen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(5));
            repo.SaveFullScreen.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(6));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(7));
            repo.SaveFullScreen.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemJpegFilesAsteriskJpgAsteri' at 799;7.", repo.List1000.ListItemJpegFilesAsteriskJpgAsteriInfo, new RecordItemIndex(8));
            repo.List1000.ListItemJpegFilesAsteriskJpgAsteri.Click("799;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveFullScreen.Text1001' at 780;7.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(9));
            repo.SaveFullScreen.Text1001.DoubleClick("780;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(10));
            repo.SaveFullScreen.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen'.", new RecordItemIndex(11));
            Keyboard.Press("D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(12));
            repo.SaveFullScreen.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveFullScreen' at Center.", repo.SnapXAutoRunModeUntitled.SaveFullScreenInfo, new RecordItemIndex(13));
            repo.SnapXAutoRunModeUntitled.SaveFullScreen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(14));
            repo.SaveFullScreen.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(15));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(16));
            repo.SaveFullScreen.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemTiffFilesAsteriskTifAsteri' at 790;9.", repo.List1000.ListItemTiffFilesAsteriskTifAsteriInfo, new RecordItemIndex(17));
            repo.List1000.ListItemTiffFilesAsteriskTifAsteri.Click("790;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveFullScreen.Text1001' at 780;7.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(18));
            repo.SaveFullScreen.Text1001.DoubleClick("780;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(19));
            repo.SaveFullScreen.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen'.", new RecordItemIndex(20));
            Keyboard.Press("D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(21));
            repo.SaveFullScreen.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveFullScreen' at Center.", repo.SnapXAutoRunModeUntitled.SaveFullScreenInfo, new RecordItemIndex(22));
            repo.SnapXAutoRunModeUntitled.SaveFullScreen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(23));
            repo.SaveFullScreen.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(24));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(25));
            repo.SaveFullScreen.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemGifFilesAsteriskGif' at 789;8.", repo.List1000.ListItemGifFilesAsteriskGifInfo, new RecordItemIndex(26));
            repo.List1000.ListItemGifFilesAsteriskGif.Click("789;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveFullScreen.Text1001' at 780;7.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(27));
            repo.SaveFullScreen.Text1001.DoubleClick("780;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(28));
            repo.SaveFullScreen.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen'.", new RecordItemIndex(29));
            Keyboard.Press("D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(30));
            repo.SaveFullScreen.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveFullScreen' at Center.", repo.SnapXAutoRunModeUntitled.SaveFullScreenInfo, new RecordItemIndex(31));
            repo.SnapXAutoRunModeUntitled.SaveFullScreen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(32));
            repo.SaveFullScreen.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(33));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(34));
            repo.SaveFullScreen.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemTargaFilesAsteriskTga' at 793;7.", repo.List1000.ListItemTargaFilesAsteriskTgaInfo, new RecordItemIndex(35));
            repo.List1000.ListItemTargaFilesAsteriskTga.Click("793;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveFullScreen.Text1001' at 780;7.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(36));
            repo.SaveFullScreen.Text1001.DoubleClick("780;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(37));
            repo.SaveFullScreen.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen'.", new RecordItemIndex(38));
            Keyboard.Press("D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(39));
            repo.SaveFullScreen.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveFullScreen' at Center.", repo.SnapXAutoRunModeUntitled.SaveFullScreenInfo, new RecordItemIndex(40));
            repo.SnapXAutoRunModeUntitled.SaveFullScreen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(41));
            repo.SaveFullScreen.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(42));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(43));
            repo.SaveFullScreen.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemPortableNetworkGraphicsFiles' at 789;6.", repo.List1000.ListItemPortableNetworkGraphicsFilesInfo, new RecordItemIndex(44));
            repo.List1000.ListItemPortableNetworkGraphicsFiles.Click("789;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveFullScreen.Text1001' at 780;7.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(45));
            repo.SaveFullScreen.Text1001.DoubleClick("780;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(46));
            repo.SaveFullScreen.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen'.", new RecordItemIndex(47));
            Keyboard.Press("D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(48));
            repo.SaveFullScreen.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveFullScreen' at Center.", repo.SnapXAutoRunModeUntitled.SaveFullScreenInfo, new RecordItemIndex(49));
            repo.SnapXAutoRunModeUntitled.SaveFullScreen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(50));
            repo.SaveFullScreen.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(51));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveFullScreen.DropDown' at Center.", repo.SaveFullScreen.DropDownInfo, new RecordItemIndex(52));
            repo.SaveFullScreen.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemPDFFilesAsteriskPdf' at 795;6.", repo.List1000.ListItemPDFFilesAsteriskPdfInfo, new RecordItemIndex(53));
            repo.List1000.ListItemPDFFilesAsteriskPdf.Click("795;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveFullScreen.Text1001' at 780;7.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(54));
            repo.SaveFullScreen.Text1001.DoubleClick("780;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(55));
            repo.SaveFullScreen.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen'.", new RecordItemIndex(56));
            Keyboard.Press("D:\\Joro\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\fullscreen");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveFullScreen.Text1001'.", repo.SaveFullScreen.Text1001Info, new RecordItemIndex(57));
            repo.SaveFullScreen.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveFullScreen' at 47;18.", repo.SnapXAutoRunModeUntitled.SaveFullScreenInfo, new RecordItemIndex(58));
            repo.SnapXAutoRunModeUntitled.SaveFullScreen.Click("47;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SNAPX.SaveImageAs' at Center.", repo.SNAPX.SaveImageAsInfo, new RecordItemIndex(59));
            repo.SNAPX.SaveImageAs.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Escape}'.", new RecordItemIndex(60));
            Keyboard.Press("{Escape}");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
