///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SaveImage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SaveImageRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("90d8d3e5-da2b-4209-bfdc-a2ba6b3ed884")]
    public partial class SaveImageRepository : RepoGenBaseFolder
    {
        static SaveImageRepository instance = new SaveImageRepository();
        SaveImageRepositoryFolders.SnapXAutoRunModeUntitledAppFolder _snapxautorunmodeuntitled;
        SaveImageRepositoryFolders.SaveImageAppFolder _saveimage;
        SaveImageRepositoryFolders.List1000AppFolder _list1000;
        SaveImageRepositoryFolders.SNAPXAppFolder _snapx;
        SaveImageRepositoryFolders.SaveImageAndTargetAppFolder _saveimageandtarget;
        SaveImageRepositoryFolders.SaveFullScreenAppFolder _savefullscreen;

        /// <summary>
        /// Gets the singleton class instance representing the SaveImageRepository element repository.
        /// </summary>
        [RepositoryFolder("90d8d3e5-da2b-4209-bfdc-a2ba6b3ed884")]
        public static SaveImageRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SaveImageRepository() 
            : base("SaveImageRepository", "/", null, 0, false, "90d8d3e5-da2b-4209-bfdc-a2ba6b3ed884", ".\\RepositoryImages\\SaveImageRepository90d8d3e5.rximgres")
        {
            _snapxautorunmodeuntitled = new SaveImageRepositoryFolders.SnapXAutoRunModeUntitledAppFolder(this);
            _saveimage = new SaveImageRepositoryFolders.SaveImageAppFolder(this);
            _list1000 = new SaveImageRepositoryFolders.List1000AppFolder(this);
            _snapx = new SaveImageRepositoryFolders.SNAPXAppFolder(this);
            _saveimageandtarget = new SaveImageRepositoryFolders.SaveImageAndTargetAppFolder(this);
            _savefullscreen = new SaveImageRepositoryFolders.SaveFullScreenAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("90d8d3e5-da2b-4209-bfdc-a2ba6b3ed884")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXAutoRunModeUntitled folder.
        /// </summary>
        [RepositoryFolder("8cc8b891-a104-4bf4-9ce1-10f9ceec734c")]
        public virtual SaveImageRepositoryFolders.SnapXAutoRunModeUntitledAppFolder SnapXAutoRunModeUntitled
        {
            get { return _snapxautorunmodeuntitled; }
        }

        /// <summary>
        /// The SaveImage folder.
        /// </summary>
        [RepositoryFolder("67efbc95-e046-48d3-86ea-25ce0cf04549")]
        public virtual SaveImageRepositoryFolders.SaveImageAppFolder SaveImage
        {
            get { return _saveimage; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("c38525d8-ac39-4667-b1ee-8a886d9f2809")]
        public virtual SaveImageRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The SNAPX folder.
        /// </summary>
        [RepositoryFolder("d8fede7c-e6e9-4157-a158-e288b63cd93b")]
        public virtual SaveImageRepositoryFolders.SNAPXAppFolder SNAPX
        {
            get { return _snapx; }
        }

        /// <summary>
        /// The SaveImageAndTarget folder.
        /// </summary>
        [RepositoryFolder("f473f00b-dda9-45c0-8133-27307fe93507")]
        public virtual SaveImageRepositoryFolders.SaveImageAndTargetAppFolder SaveImageAndTarget
        {
            get { return _saveimageandtarget; }
        }

        /// <summary>
        /// The SaveFullScreen folder.
        /// </summary>
        [RepositoryFolder("7e9fa0b1-eb11-4ce8-bc1a-6d60a252c05d")]
        public virtual SaveImageRepositoryFolders.SaveFullScreenAppFolder SaveFullScreen
        {
            get { return _savefullscreen; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class SaveImageRepositoryFolders
    {
        /// <summary>
        /// The SnapXAutoRunModeUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("8cc8b891-a104-4bf4-9ce1-10f9ceec734c")]
        public partial class SnapXAutoRunModeUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _saveimageInfo;
            RepoItemInfo _saveimageandtargetInfo;
            RepoItemInfo _boxtargetInfo;
            RepoItemInfo _savefullscreenInfo;

            /// <summary>
            /// Creates a new SnapXAutoRunModeUntitled  folder.
            /// </summary>
            public SnapXAutoRunModeUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SNAPXAutoRunModeUntitled", "/form[@title='SNAP-X - [Untitled]']", parentFolder, 30000, null, true, "8cc8b891-a104-4bf4-9ce1-10f9ceec734c", "")
            {
                _saveimageInfo = new RepoItemInfo(this, "SaveImage", "?/?/form//toolbar/button[@text='Save Image' and @commandid='32903']", 30000, null, "b84598ab-935e-4618-932e-d8315a9beb30");
                _saveimageandtargetInfo = new RepoItemInfo(this, "SaveImageAndTarget", "?/?/form//toolbar/button[@text='Save Image and Target' and @commandid='32904']", 30000, null, "bf41c5fb-c563-4bdd-a13c-3644b1b3d23c");
                _boxtargetInfo = new RepoItemInfo(this, "BoxTarget", "container/form//toolbar/button[@commandid='5011']", 30000, null, "6fe3f072-24f7-464e-bb83-c8c95d285dd5");
                _savefullscreenInfo = new RepoItemInfo(this, "SaveFullScreen", "?/?/form//toolbar/button[@text='Save Full Screen' and @commandid='32905']", 30000, null, "2db7d482-1486-438e-9aa8-bcebec1ac3c8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8cc8b891-a104-4bf4-9ce1-10f9ceec734c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8cc8b891-a104-4bf4-9ce1-10f9ceec734c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SaveImage item.
            /// </summary>
            [RepositoryItem("b84598ab-935e-4618-932e-d8315a9beb30")]
            public virtual Ranorex.Button SaveImage
            {
                get
                {
                    return _saveimageInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveImage item info.
            /// </summary>
            [RepositoryItemInfo("b84598ab-935e-4618-932e-d8315a9beb30")]
            public virtual RepoItemInfo SaveImageInfo
            {
                get
                {
                    return _saveimageInfo;
                }
            }

            /// <summary>
            /// The SaveImageAndTarget item.
            /// </summary>
            [RepositoryItem("bf41c5fb-c563-4bdd-a13c-3644b1b3d23c")]
            public virtual Ranorex.Button SaveImageAndTarget
            {
                get
                {
                    return _saveimageandtargetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveImageAndTarget item info.
            /// </summary>
            [RepositoryItemInfo("bf41c5fb-c563-4bdd-a13c-3644b1b3d23c")]
            public virtual RepoItemInfo SaveImageAndTargetInfo
            {
                get
                {
                    return _saveimageandtargetInfo;
                }
            }

            /// <summary>
            /// The BoxTarget item.
            /// </summary>
            [RepositoryItem("6fe3f072-24f7-464e-bb83-c8c95d285dd5")]
            public virtual Ranorex.Button BoxTarget
            {
                get
                {
                    return _boxtargetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BoxTarget item info.
            /// </summary>
            [RepositoryItemInfo("6fe3f072-24f7-464e-bb83-c8c95d285dd5")]
            public virtual RepoItemInfo BoxTargetInfo
            {
                get
                {
                    return _boxtargetInfo;
                }
            }

            /// <summary>
            /// The SaveFullScreen item.
            /// </summary>
            [RepositoryItem("2db7d482-1486-438e-9aa8-bcebec1ac3c8")]
            public virtual Ranorex.Button SaveFullScreen
            {
                get
                {
                    return _savefullscreenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveFullScreen item info.
            /// </summary>
            [RepositoryItemInfo("2db7d482-1486-438e-9aa8-bcebec1ac3c8")]
            public virtual RepoItemInfo SaveFullScreenInfo
            {
                get
                {
                    return _savefullscreenInfo;
                }
            }
        }

        /// <summary>
        /// The SaveImageAppFolder folder.
        /// </summary>
        [RepositoryFolder("67efbc95-e046-48d3-86ea-25ce0cf04549")]
        public partial class SaveImageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1001Info;
            RepoItemInfo _dropdownInfo;

            /// <summary>
            /// Creates a new SaveImage  folder.
            /// </summary>
            public SaveImageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveImage", "/form[@title='Save Image']", parentFolder, 30000, null, true, "67efbc95-e046-48d3-86ea-25ce0cf04549", "")
            {
                _text1001Info = new RepoItemInfo(this, "Text1001", "element[@class='DUIViewWndClassName']//combobox[@class='ComboBox']/text[@controlid='1001']", 30000, null, "a41fe222-b950-4b1d-9cc8-e8fb95c8b541");
                _dropdownInfo = new RepoItemInfo(this, "DropDown", "element[@class='DUIViewWndClassName']/container/element[4]/combobox[@class='ComboBox']/button[@automationid='DropDown']", 30000, null, "62d77944-caab-493b-941b-ea93b889795e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("67efbc95-e046-48d3-86ea-25ce0cf04549")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("67efbc95-e046-48d3-86ea-25ce0cf04549")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("a41fe222-b950-4b1d-9cc8-e8fb95c8b541")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("a41fe222-b950-4b1d-9cc8-e8fb95c8b541")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The DropDown item.
            /// </summary>
            [RepositoryItem("62d77944-caab-493b-941b-ea93b889795e")]
            public virtual Ranorex.Button DropDown
            {
                get
                {
                    return _dropdownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DropDown item info.
            /// </summary>
            [RepositoryItemInfo("62d77944-caab-493b-941b-ea93b889795e")]
            public virtual RepoItemInfo DropDownInfo
            {
                get
                {
                    return _dropdownInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("c38525d8-ac39-4667-b1ee-8a886d9f2809")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _listitemjpegfilesasteriskjpgasteriInfo;
            RepoItemInfo _listitemtifffilesasterisktifasteriInfo;
            RepoItemInfo _listitemgiffilesasteriskgifInfo;
            RepoItemInfo _listitemtargafilesasterisktgaInfo;
            RepoItemInfo _listitemportablenetworkgraphicsfilesInfo;
            RepoItemInfo _listitempdffilesasteriskpdfInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "c38525d8-ac39-4667-b1ee-8a886d9f2809", "")
            {
                _listitemjpegfilesasteriskjpgasteriInfo = new RepoItemInfo(this, "ListItemJpegFilesAsteriskJpgAsteri", "listitem[@text~'^\\ Jpeg\\ Files\\ \\(\\*\\.jpg;\\*\\.jpeg']", 30000, null, "dd6dfd2e-2c25-40aa-9b7a-7f05c83a227a");
                _listitemtifffilesasterisktifasteriInfo = new RepoItemInfo(this, "ListItemTiffFilesAsteriskTifAsteri", "listitem[@text~'^\\ Tiff\\ Files\\ \\(\\*\\.tif;\\*\\.tiff']", 30000, null, "bba97575-86cd-4d76-8a13-b214db5090a3");
                _listitemgiffilesasteriskgifInfo = new RepoItemInfo(this, "ListItemGifFilesAsteriskGif", "listitem[@text=' Gif Files (*.gif)']", 30000, null, "5d361c4a-9d01-4ef0-9638-4d116c34ad93");
                _listitemtargafilesasterisktgaInfo = new RepoItemInfo(this, "ListItemTargaFilesAsteriskTga", "listitem[@text=' Targa Files (*.tga)']", 30000, null, "604702f4-6b8d-46fd-acd7-c1d9a49debc4");
                _listitemportablenetworkgraphicsfilesInfo = new RepoItemInfo(this, "ListItemPortableNetworkGraphicsFiles", "listitem[@text~'^\\ Portable\\ Network\\ Graphic']", 30000, null, "96f651a6-f822-4906-8bf1-89ef4b5f25fb");
                _listitempdffilesasteriskpdfInfo = new RepoItemInfo(this, "ListItemPDFFilesAsteriskPdf", "listitem[@text=' PDF Files (*.pdf)']", 30000, null, "6d311a65-7c00-491d-bbe0-cc9fd58e1110");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c38525d8-ac39-4667-b1ee-8a886d9f2809")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c38525d8-ac39-4667-b1ee-8a886d9f2809")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItemJpegFilesAsteriskJpgAsteri item.
            /// </summary>
            [RepositoryItem("dd6dfd2e-2c25-40aa-9b7a-7f05c83a227a")]
            public virtual Ranorex.ListItem ListItemJpegFilesAsteriskJpgAsteri
            {
                get
                {
                    return _listitemjpegfilesasteriskjpgasteriInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemJpegFilesAsteriskJpgAsteri item info.
            /// </summary>
            [RepositoryItemInfo("dd6dfd2e-2c25-40aa-9b7a-7f05c83a227a")]
            public virtual RepoItemInfo ListItemJpegFilesAsteriskJpgAsteriInfo
            {
                get
                {
                    return _listitemjpegfilesasteriskjpgasteriInfo;
                }
            }

            /// <summary>
            /// The ListItemTiffFilesAsteriskTifAsteri item.
            /// </summary>
            [RepositoryItem("bba97575-86cd-4d76-8a13-b214db5090a3")]
            public virtual Ranorex.ListItem ListItemTiffFilesAsteriskTifAsteri
            {
                get
                {
                    return _listitemtifffilesasterisktifasteriInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemTiffFilesAsteriskTifAsteri item info.
            /// </summary>
            [RepositoryItemInfo("bba97575-86cd-4d76-8a13-b214db5090a3")]
            public virtual RepoItemInfo ListItemTiffFilesAsteriskTifAsteriInfo
            {
                get
                {
                    return _listitemtifffilesasterisktifasteriInfo;
                }
            }

            /// <summary>
            /// The ListItemGifFilesAsteriskGif item.
            /// </summary>
            [RepositoryItem("5d361c4a-9d01-4ef0-9638-4d116c34ad93")]
            public virtual Ranorex.ListItem ListItemGifFilesAsteriskGif
            {
                get
                {
                    return _listitemgiffilesasteriskgifInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemGifFilesAsteriskGif item info.
            /// </summary>
            [RepositoryItemInfo("5d361c4a-9d01-4ef0-9638-4d116c34ad93")]
            public virtual RepoItemInfo ListItemGifFilesAsteriskGifInfo
            {
                get
                {
                    return _listitemgiffilesasteriskgifInfo;
                }
            }

            /// <summary>
            /// The ListItemTargaFilesAsteriskTga item.
            /// </summary>
            [RepositoryItem("604702f4-6b8d-46fd-acd7-c1d9a49debc4")]
            public virtual Ranorex.ListItem ListItemTargaFilesAsteriskTga
            {
                get
                {
                    return _listitemtargafilesasterisktgaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemTargaFilesAsteriskTga item info.
            /// </summary>
            [RepositoryItemInfo("604702f4-6b8d-46fd-acd7-c1d9a49debc4")]
            public virtual RepoItemInfo ListItemTargaFilesAsteriskTgaInfo
            {
                get
                {
                    return _listitemtargafilesasterisktgaInfo;
                }
            }

            /// <summary>
            /// The ListItemPortableNetworkGraphicsFiles item.
            /// </summary>
            [RepositoryItem("96f651a6-f822-4906-8bf1-89ef4b5f25fb")]
            public virtual Ranorex.ListItem ListItemPortableNetworkGraphicsFiles
            {
                get
                {
                    return _listitemportablenetworkgraphicsfilesInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPortableNetworkGraphicsFiles item info.
            /// </summary>
            [RepositoryItemInfo("96f651a6-f822-4906-8bf1-89ef4b5f25fb")]
            public virtual RepoItemInfo ListItemPortableNetworkGraphicsFilesInfo
            {
                get
                {
                    return _listitemportablenetworkgraphicsfilesInfo;
                }
            }

            /// <summary>
            /// The ListItemPDFFilesAsteriskPdf item.
            /// </summary>
            [RepositoryItem("6d311a65-7c00-491d-bbe0-cc9fd58e1110")]
            public virtual Ranorex.ListItem ListItemPDFFilesAsteriskPdf
            {
                get
                {
                    return _listitempdffilesasteriskpdfInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPDFFilesAsteriskPdf item info.
            /// </summary>
            [RepositoryItemInfo("6d311a65-7c00-491d-bbe0-cc9fd58e1110")]
            public virtual RepoItemInfo ListItemPDFFilesAsteriskPdfInfo
            {
                get
                {
                    return _listitempdffilesasteriskpdfInfo;
                }
            }
        }

        /// <summary>
        /// The SNAPXAppFolder folder.
        /// </summary>
        [RepositoryFolder("d8fede7c-e6e9-4157-a158-e288b63cd93b")]
        public partial class SNAPXAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _saveimageandtargetasInfo;
            RepoItemInfo _savefullscreenasInfo;
            RepoItemInfo _saveimageasInfo;

            /// <summary>
            /// Creates a new SNAPX  folder.
            /// </summary>
            public SNAPXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SNAPX", "/contextmenu[@processname='SNAP-X']", parentFolder, 30000, null, false, "d8fede7c-e6e9-4157-a158-e288b63cd93b", "")
            {
                _saveimageandtargetasInfo = new RepoItemInfo(this, "SaveImageAndTargetAs", "?/?/menuitem[@accessiblename~'^Save\\ Image\\ and\\ Target\\ As\\.']", 30000, null, "5232e64a-837b-44a6-8a94-3fe9c69cea10");
                _savefullscreenasInfo = new RepoItemInfo(this, "SaveFullScreenAs", "?/?/menuitem[@accessiblename='Save Full Screen As...']", 30000, null, "2f71b9df-79ef-4a84-b399-6c13f9dc3774");
                _saveimageasInfo = new RepoItemInfo(this, "SaveImageAs", "?/?/menuitem[@accessiblename='Save Image As...']", 30000, null, "9abe347c-f926-4222-b250-ab9c14b0b1d5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d8fede7c-e6e9-4157-a158-e288b63cd93b")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d8fede7c-e6e9-4157-a158-e288b63cd93b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SaveImageAndTargetAs item.
            /// </summary>
            [RepositoryItem("5232e64a-837b-44a6-8a94-3fe9c69cea10")]
            public virtual Ranorex.MenuItem SaveImageAndTargetAs
            {
                get
                {
                    return _saveimageandtargetasInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SaveImageAndTargetAs item info.
            /// </summary>
            [RepositoryItemInfo("5232e64a-837b-44a6-8a94-3fe9c69cea10")]
            public virtual RepoItemInfo SaveImageAndTargetAsInfo
            {
                get
                {
                    return _saveimageandtargetasInfo;
                }
            }

            /// <summary>
            /// The SaveFullScreenAs item.
            /// </summary>
            [RepositoryItem("2f71b9df-79ef-4a84-b399-6c13f9dc3774")]
            public virtual Ranorex.MenuItem SaveFullScreenAs
            {
                get
                {
                    return _savefullscreenasInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SaveFullScreenAs item info.
            /// </summary>
            [RepositoryItemInfo("2f71b9df-79ef-4a84-b399-6c13f9dc3774")]
            public virtual RepoItemInfo SaveFullScreenAsInfo
            {
                get
                {
                    return _savefullscreenasInfo;
                }
            }

            /// <summary>
            /// The SaveImageAs item.
            /// </summary>
            [RepositoryItem("9abe347c-f926-4222-b250-ab9c14b0b1d5")]
            public virtual Ranorex.MenuItem SaveImageAs
            {
                get
                {
                    return _saveimageasInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SaveImageAs item info.
            /// </summary>
            [RepositoryItemInfo("9abe347c-f926-4222-b250-ab9c14b0b1d5")]
            public virtual RepoItemInfo SaveImageAsInfo
            {
                get
                {
                    return _saveimageasInfo;
                }
            }
        }

        /// <summary>
        /// The SaveImageAndTargetAppFolder folder.
        /// </summary>
        [RepositoryFolder("f473f00b-dda9-45c0-8133-27307fe93507")]
        public partial class SaveImageAndTargetAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1001Info;
            RepoItemInfo _dropdownInfo;

            /// <summary>
            /// Creates a new SaveImageAndTarget  folder.
            /// </summary>
            public SaveImageAndTargetAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveImageAndTarget", "/form[@title='Save Image and Target']", parentFolder, 30000, null, true, "f473f00b-dda9-45c0-8133-27307fe93507", "")
            {
                _text1001Info = new RepoItemInfo(this, "Text1001", "element[@class='DUIViewWndClassName']//combobox[@class='ComboBox']/text[@controlid='1001']", 30000, null, "5b1013c4-5f17-422b-903c-7a70e3044a8e");
                _dropdownInfo = new RepoItemInfo(this, "DropDown", "element[@class='DUIViewWndClassName']/container/element[4]/combobox[@class='ComboBox']/button[@automationid='DropDown']", 30000, null, "7f0f5408-694b-44a6-90b4-c3eaf6c5b1e1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f473f00b-dda9-45c0-8133-27307fe93507")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f473f00b-dda9-45c0-8133-27307fe93507")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("5b1013c4-5f17-422b-903c-7a70e3044a8e")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("5b1013c4-5f17-422b-903c-7a70e3044a8e")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The DropDown item.
            /// </summary>
            [RepositoryItem("7f0f5408-694b-44a6-90b4-c3eaf6c5b1e1")]
            public virtual Ranorex.Button DropDown
            {
                get
                {
                    return _dropdownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DropDown item info.
            /// </summary>
            [RepositoryItemInfo("7f0f5408-694b-44a6-90b4-c3eaf6c5b1e1")]
            public virtual RepoItemInfo DropDownInfo
            {
                get
                {
                    return _dropdownInfo;
                }
            }
        }

        /// <summary>
        /// The SaveFullScreenAppFolder folder.
        /// </summary>
        [RepositoryFolder("7e9fa0b1-eb11-4ce8-bc1a-6d60a252c05d")]
        public partial class SaveFullScreenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1001Info;
            RepoItemInfo _dropdownInfo;

            /// <summary>
            /// Creates a new SaveFullScreen  folder.
            /// </summary>
            public SaveFullScreenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveFullScreen", "/form[@title='Save Full Screen']", parentFolder, 30000, null, true, "7e9fa0b1-eb11-4ce8-bc1a-6d60a252c05d", "")
            {
                _text1001Info = new RepoItemInfo(this, "Text1001", "element[@class='DUIViewWndClassName']//combobox[@class='ComboBox']/text[@controlid='1001']", 30000, null, "1947a73e-0a4d-4eb2-a7cf-6c779743ee65");
                _dropdownInfo = new RepoItemInfo(this, "DropDown", "element[@class='DUIViewWndClassName']/container/element[4]/combobox[@class='ComboBox']/button[@automationid='DropDown']", 30000, null, "d1769cf1-495f-44ff-9972-47cd80b29d82");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7e9fa0b1-eb11-4ce8-bc1a-6d60a252c05d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7e9fa0b1-eb11-4ce8-bc1a-6d60a252c05d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("1947a73e-0a4d-4eb2-a7cf-6c779743ee65")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("1947a73e-0a4d-4eb2-a7cf-6c779743ee65")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The DropDown item.
            /// </summary>
            [RepositoryItem("d1769cf1-495f-44ff-9972-47cd80b29d82")]
            public virtual Ranorex.Button DropDown
            {
                get
                {
                    return _dropdownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DropDown item info.
            /// </summary>
            [RepositoryItemInfo("d1769cf1-495f-44ff-9972-47cd80b29d82")]
            public virtual RepoItemInfo DropDownInfo
            {
                get
                {
                    return _dropdownInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}