///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SaveImage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SaveImageWithTarget recording.
    /// </summary>
    [TestModule("e8ceabbb-3738-4ce3-b22a-feabed3477d7", ModuleType.Recording, 1)]
    public partial class SaveImageWithTarget : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SaveImageRepository repository.
        /// </summary>
        public static SaveImageRepository repo = SaveImageRepository.Instance;

        static SaveImageWithTarget instance = new SaveImageWithTarget();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SaveImageWithTarget()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SaveImageWithTarget Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveImageAndTarget.Text1001' at 777;8.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(0));
            repo.SaveImageAndTarget.Text1001.DoubleClick("777;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(1));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target'.", new RecordItemIndex(2));
            Keyboard.Press("C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(3));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveImageAndTarget' at Center.", repo.SnapXAutoRunModeUntitled.SaveImageAndTargetInfo, new RecordItemIndex(4));
            repo.SnapXAutoRunModeUntitled.SaveImageAndTarget.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(5));
            repo.SaveImageAndTarget.DropDown.MoveTo();
            Delay.Milliseconds(200);


            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(6));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(7));
            repo.SaveImageAndTarget.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemJpegFilesAsteriskJpgAsteri' at 797;8.", repo.List1000.ListItemJpegFilesAsteriskJpgAsteriInfo, new RecordItemIndex(8));
            repo.List1000.ListItemJpegFilesAsteriskJpgAsteri.Click("797;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveImageAndTarget.Text1001' at 781;8.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(9));
            repo.SaveImageAndTarget.Text1001.DoubleClick("781;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(10));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target'.", new RecordItemIndex(11));
            Keyboard.Press("C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(12));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveImageAndTarget' at Center.", repo.SnapXAutoRunModeUntitled.SaveImageAndTargetInfo, new RecordItemIndex(13));
            repo.SnapXAutoRunModeUntitled.SaveImageAndTarget.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(14));
            repo.SaveImageAndTarget.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(15));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(16));
            repo.SaveImageAndTarget.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemTiffFilesAsteriskTifAsteri' at 795;4.", repo.List1000.ListItemTiffFilesAsteriskTifAsteriInfo, new RecordItemIndex(17));
            repo.List1000.ListItemTiffFilesAsteriskTifAsteri.Click("795;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveImageAndTarget.Text1001' at 781;8.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(18));
            repo.SaveImageAndTarget.Text1001.DoubleClick("781;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(19));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target'.", new RecordItemIndex(20));
            Keyboard.Press("C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(21));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveImageAndTarget' at Center.", repo.SnapXAutoRunModeUntitled.SaveImageAndTargetInfo, new RecordItemIndex(22));
            repo.SnapXAutoRunModeUntitled.SaveImageAndTarget.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(23));
            repo.SaveImageAndTarget.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(24));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(25));
            repo.SaveImageAndTarget.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemGifFilesAsteriskGif' at 788;9.", repo.List1000.ListItemGifFilesAsteriskGifInfo, new RecordItemIndex(26));
            repo.List1000.ListItemGifFilesAsteriskGif.Click("788;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveImageAndTarget.Text1001' at 781;8.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(27));
            repo.SaveImageAndTarget.Text1001.DoubleClick("781;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(28));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target'.", new RecordItemIndex(29));
            Keyboard.Press("C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(30));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveImageAndTarget' at Center.", repo.SnapXAutoRunModeUntitled.SaveImageAndTargetInfo, new RecordItemIndex(31));
            repo.SnapXAutoRunModeUntitled.SaveImageAndTarget.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(32));
            repo.SaveImageAndTarget.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(33));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(34));
            repo.SaveImageAndTarget.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemTargaFilesAsteriskTga' at 787;7.", repo.List1000.ListItemTargaFilesAsteriskTgaInfo, new RecordItemIndex(35));
            repo.List1000.ListItemTargaFilesAsteriskTga.Click("787;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveImageAndTarget.Text1001' at 781;8.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(36));
            repo.SaveImageAndTarget.Text1001.DoubleClick("781;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(37));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target'.", new RecordItemIndex(38));
            Keyboard.Press("C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(39));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveImageAndTarget' at Center.", repo.SnapXAutoRunModeUntitled.SaveImageAndTargetInfo, new RecordItemIndex(40));
            repo.SnapXAutoRunModeUntitled.SaveImageAndTarget.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(41));
            repo.SaveImageAndTarget.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(42));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(43));
            repo.SaveImageAndTarget.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemPortableNetworkGraphicsFiles' at 791;7.", repo.List1000.ListItemPortableNetworkGraphicsFilesInfo, new RecordItemIndex(44));
            repo.List1000.ListItemPortableNetworkGraphicsFiles.Click("791;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveImageAndTarget.Text1001' at 781;8.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(45));
            repo.SaveImageAndTarget.Text1001.DoubleClick("781;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(46));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target'.", new RecordItemIndex(47));
            Keyboard.Press("C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(48));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveImageAndTarget' at Center.", repo.SnapXAutoRunModeUntitled.SaveImageAndTargetInfo, new RecordItemIndex(49));
            repo.SnapXAutoRunModeUntitled.SaveImageAndTarget.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(50));
            repo.SaveImageAndTarget.DropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(51));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveImageAndTarget.DropDown' at Center.", repo.SaveImageAndTarget.DropDownInfo, new RecordItemIndex(52));
            repo.SaveImageAndTarget.DropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemPDFFilesAsteriskPdf' at 796;7.", repo.List1000.ListItemPDFFilesAsteriskPdfInfo, new RecordItemIndex(53));
            repo.List1000.ListItemPDFFilesAsteriskPdf.Click("796;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SaveImageAndTarget.Text1001' at 781;8.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(54));
            repo.SaveImageAndTarget.Text1001.DoubleClick("781;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(55));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Delete}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target'.", new RecordItemIndex(56));
            Keyboard.Press("C:\\JORO\\AUTOMATIONS\\GIT_Automations\\VERSION 3\\AutomationImages\\Reports\\target");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'SaveImageAndTarget.Text1001'.", repo.SaveImageAndTarget.Text1001Info, new RecordItemIndex(57));
            repo.SaveImageAndTarget.Text1001.PressKeys("{Return}");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXAutoRunModeUntitled.SaveImageAndTarget' at 48;18.", repo.SnapXAutoRunModeUntitled.SaveImageAndTargetInfo, new RecordItemIndex(58));
            repo.SnapXAutoRunModeUntitled.SaveImageAndTarget.Click("48;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SNAPX.SaveFullScreenAs' at Center.", repo.SNAPX.SaveFullScreenAsInfo, new RecordItemIndex(59));
            repo.SNAPX.SaveFullScreenAs.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
